name: Docker Build & Push

on:
   push:
      branches: [main]

jobs:
    build-and-push:
        runs-on: latest-ubuntu

        steps:

            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKER_USER }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}
           
            - name: Build Dockerfile
              run: Build -t ${{ secrets.DOCKER_USER }}/cicd-app .

            - name: docker to Docker hub
              run: docker push ${{ secrets.DOCKER_USER }}/cicd-app


     deploy-ec2:
      runs-on: ubuntu-latest
      needs: build-and-push

      steps:
        - name: Deploy to EC2
          uses: appleboy/ssh-action@v1.2.2
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
            script: |
              cd /home/ubuntu/actions-runner
              docker compose down
              docker compose up -d --build
       


            

          

                
             

            

                